### ISSUE TITLE
add minimal metadata to JSON output

### ISSUE THREAD

**Issue by dasch124** [acdh-oeaw/acdh-baserow-pyutils#30]
it would be cool if  the JSON dump would contain some minimal metadata:

* ID and name of the table 
* base-url of the baserow instance 
* database ID
* timestamp

The latter three can be added by the calling script, but the table ID is only known to the function.

**Comment by csae8092** [comment]
I'd like to keep those two things separate, but with https://github.com/acdh-oeaw/baserow-dump-cookiecutter/issues/1 in place, we would have the data and some structured metadata in one file

see here for a current implementation https://github.com/teaching-paradimes/teaching-paradimes-baserow-export/blob/1-serialize-json-dumps-as-teixml/make_tei.py

should be ready next week

**Comment by csae8092** [comment]
here is an example of the current TEI/XML https://github.com/teaching-paradimes/teaching-paradimes-baserow-export/blob/1-serialize-json-dumps-as-teixml/tei/courses.xml
