### ISSUE TITLE
UTF-8 encoding error

### ISSUE THREAD

**Issue by dasch124** [acdh-oeaw/acdh-baserow-pyutils#39]
It seems that on Windows the package tries to encode the downloaded JSON as cp1252. This creates problems when the data in baserow contains characters outside the code page.

![grafik](https://github.com/user-attachments/assets/5273bda3-2618-437a-ab4f-f47db4794321)

I suppose, this can be solved by explicitly setting the file encoding in line https://github.com/acdh-oeaw/acdh-baserow-pyutils/blob/main/acdh_baserow_pyutils/__init__.py#L116

**Comment by simar0at** [comment]
For Windows compatibility all open and write calls should have the encoding parameter set. See https://docs.python.org/3/tutorial/inputoutput.html#reading-and-writing-files  
Unfortunately python on Windows defaults to the "System Codepage" which is cp1252 in Europe.

**Comment by simar0at** [comment]
There is an environment variable `PYTHONUTF8=1` that switches python to using UTF-8 on Windows.  
If you want to set this on a Laptop or PC and you have no admin rights (company issued) use
```powershell
rundll32 sysdm.cpl,EditEnvironmentVariables
```
The UI lets you change the environment variables for your user account and is not accessible without administrator rights using system settings.

**Comment by simar0at** [comment]
Getestet. Das Problem ist behoben.
